version: '3.5'
services:
  ecommerce_db:
    image: mysql:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_DATABASE: dba_ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
      MYSQL_ROOT_PASSWORD: ecommerce
    volumes:
      - ./data_mysql:/var/lib/mysql
  ecommerce_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_django_dir
    ports:
      - "8001:8000"
    depends_on:
      - ecommerce_db
