# Generated by Django 3.2.5 on 2022-01-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='cat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
    ]
